# =========================================
# Application
# =========================================
spring.application.name=event-ticketing

# =========================================
# Server
# =========================================
server.port=8080


# =========================================
# PostgreSQL Database
# =========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/event_ticketing
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!


# =========================================
# JPA / Hibernate
# =========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================================================
# Keycloak / OAuth2 Resource Server
# =========================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/event-ticketing
